baseURL = "http://example.org/"
languageCode = "en-us"
title = "Agnes Site"
theme = "agnes-hugo-theme"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "TeleProxy.Store"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
	[[menu.main]]
		Name = "Term & Service"
		URL = "#"
		weight = 5
		
[params.social]
	TwitterURL = "https://twitter.com/podbharati"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/podbharati"
		
[params.content]
	LeadTitle = "Secure & Fast Proxy Made For Telegram"
	LeadDescription = "One-click Proxy Setup To Unlock The Best of Telegram. Staring at $1/month"
	ButtonCaption = "Unlock Now"
	ButtonURL = "http://teleproxy.store"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Setup Once, Use Forever"
	FeatureDescription = "Hassle-free setup, use on any device"
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Top-notch Encryption"
	FeatureDescription = "Enjoy the same E2E encryption of Telegram that you love"
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Fast Connection"
	FeatureDescription = "Instant messages delivery, no lag, no hickup"
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "24/7 Reliable Access"
	FeatureDescription = "Our Proxy always work, simple as that"
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Starter"
	PricingRate = "27"	
	ButtonCaption = "Get Early Access"
 	ButtonURL = "https://example.com/early-access.html"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	

[[params.pricing]]
	PricingTitle = "Professional"
	PricingRate = "97"
	ButtonCaption = "Get Earlier Access"
 	ButtonURL = "https://example.com/earlier-access.html"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"		
	
[[params.pricing]]
	PricingTitle = "Business"
	PricingRate = "147"
	ButtonCaption = "Get Earliest Access"
 	ButtonURL = "https://example.com/earliest-access.html"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	
		